console.log("Hello, world!")
console.log("Halo, dunia!")
console.log("Ciao, mundo!")
console.log("Olá, mundo!")
console.log("Hola, mundo!")
console.log("Hallo Welt")
console.log("Zdravo svijete")
console.log("Dia duit Domhanda")
console.log("Hola món")
console.log("مرحبا بالعالم")